import vue from '@vitejs/plugin-vue'
import fs from 'fs'
import path from 'path'
import compression from 'compression'
import type { Plugin } from 'vite'
import { defineConfig } from 'vite'
import viteCompression from 'vite-plugin-compression2'

// Dev server gzip compression plugin
function devCompressionPlugin(): Plugin {
  return {
    name: 'dev-compression',
    configureServer(server) {
      server.middlewares.use(compression({ threshold: 1 }))
    },
  }
}

function httpsConfig(): false | { key: Buffer; cert: Buffer } {
  if (process.env.HOMERAIL_UI_HTTPS !== '1') return false
  const keyPath = process.env.HOMERAIL_UI_HTTPS_KEY
  const certPath = process.env.HOMERAIL_UI_HTTPS_CERT
  if (!keyPath || !certPath) {
    throw new Error('HOMERAIL_UI_HTTPS_KEY and HOMERAIL_UI_HTTPS_CERT are required when HOMERAIL_UI_HTTPS=1')
  }
  return {
    key: fs.readFileSync(keyPath),
    cert: fs.readFileSync(certPath),
  }
}

const managerPort = process.env.VITE_HOMERAIL_MANAGER_PORT || '19191'
const managerHttpTarget = process.env.VITE_API_BASE_URL || process.env.VITE_API_URL || `http://localhost:${managerPort}`
const managerWsTarget = (
  process.env.VITE_WS_URL
  || managerHttpTarget.replace(/^http:/, 'ws:').replace(/^https:/, 'wss:')
)

// NOTE: For production nginx, uncomment `gzip on;` in /usr/trim/nginx/conf/nginx.conf
// and add gzip_static on; to serve pre-compressed .gz files generated by viteCompression plugin.

export default defineConfig({
  base: './',
  plugins: [
    vue(),
    viteCompression({
      algorithms: [{
        type: 'gzip',
        algorithm: 'gzip',
      }],
      threshold: 1024,
    }),
    devCompressionPlugin(),
  ],
  css: {
    postcss: './postcss.config.js',
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src')
    },
    extensions: ['.mjs', '.js', '.ts', '.json', '.vue']
  },
  build: {
    target: 'esnext',
    sourcemap: process.env.NODE_ENV === 'development',
    chunkSizeWarningLimit: 1000
  },
  optimizeDeps: {
    include: ['vue']
  },
  server: {
    port: Number(process.env.HOMERAIL_UI_PORT || process.env.VITE_HOMERAIL_UI_PORT || 19192),
    host: true,
    https: httpsConfig(),
    hmr: {
      overlay: true
    },
    proxy: {
      '/api': {
        target: managerHttpTarget,
        ws: true,
        changeOrigin: true,
        secure: false,
        rewrite: (path) => path
      },
      '/artifacts': {
        target: managerHttpTarget,
        changeOrigin: true,
        secure: false,
        rewrite: (path) => path
      },
      '/ws': {
        target: managerWsTarget,
        ws: true,
        changeOrigin: true,
        secure: false
      }
    }
  }
})
